login_gate:
    storages: ['orm'] # Attempts storages. Available storages: ['orm', 'session', 'mongodb']
    options:
        max_count_attempts: 5
        timeout: 600 #Ban period
        watch_period: 3600 #Only for databases storage. Period of actuality attempts