translations_extra:
    default_format: 'xml'
    default_locale: 'es'
    other_locales: []
    domains: ['messages','validators']
    main_folder: '%kernel.project_dir%/translations/'
    yandex_api_key: 'trnsl.1.1.4e434e....'